name: Data Sync Service

on:
  schedule:
    - cron: '0 */2 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Env
        uses: actions/checkout@v3

      - name: Setup Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Deps
        run: pip install httpx

      - name: Process
        # 确保这里调用的是你保存的那个脚本文件名
        run: python private_hunter.py > /dev/null 2>&1

      - name: Save
        run: |
          git config --local user.email "sync@github.com"
          git config --local user.name "AutoSync"
          # 必须 add 脚本中生成的那个 bin 文件
          git add assets_manifest.bin 
          git commit -m "chore: static asset update [skip ci]" || exit 0
          git push > /dev/null 2>&1 